### PR TITLE
Update to mozprocess 1.2.1 for Py3.9 compatibility

### LINKED ISSUE #26353: `wpt run` fails to run on Python 3.9
It fails to run both Firefox and Chrome.

<details>
<summary>Log</summary>

```
> python wpt run --binary "C:\Program Files\Firefox Nightly\firefox.exe" firefox html/semantics/forms/the-input-element/selection-pointer.html
WARNING: You are using pip version 20.2.3; however, version 20.2.4 is available.
You should consider upgrading via the 'C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Scripts\python.exe -m pip install --upgrade pip' command.
Download and install geckodriver [Y/n]? y
Running 1 tests in web-platform-tests

ERROR Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
ValueError: too many values to unpack (expected 18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\testrunner.py", line 227, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 748, in start
    self.instance = self.instance_manager.get()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 350, in get
    self.pending = self.start()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 312, in start
    runner.start(debug_args=debug_args, interactive=self.debug_info and self.debug_info.interactive)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 135, in start
    reraise(RunnerNotStartedError,
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\third_party\six\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
mozrunner.errors.RunnerNotStartedError: Failed to start the process: too many values to unpack (expected 18)

INFO STDERR: Exception ignored in:
INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x00000189F97B6940>
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 174, in __del__
INFO STDERR:
INFO STDERR: if handle or self._job or self._io_port:
INFO STDERR: AttributeError
INFO STDERR: :
INFO STDERR: 'Process' object has no attribute '_job'
ERROR Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
ValueError: too many values to unpack (expected 18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\testrunner.py", line 227, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 748, in start
    self.instance = self.instance_manager.get()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 350, in get
    self.pending = self.start()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 312, in start
    runner.start(debug_args=debug_args, interactive=self.debug_info and self.debug_info.interactive)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 135, in start
    reraise(RunnerNotStartedError,
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\third_party\six\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
mozrunner.errors.RunnerNotStartedError: Failed to start the process: too many values to unpack (expected 18)

INFO STDERR: Exception ignored in:
INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x00000189F97B6940>
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 174, in __del__
INFO STDERR:
INFO STDERR: if handle or self._job or self._io_port:
INFO STDERR: AttributeError
INFO STDERR: :
INFO STDERR: 'Process' object has no attribute '_job'
ERROR Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
ValueError: too many values to unpack (expected 18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\testrunner.py", line 227, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 748, in start
    self.instance = self.instance_manager.get()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 350, in get
    self.pending = self.start()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 312, in start
    runner.start(debug_args=debug_args, interactive=self.debug_info and self.debug_info.interactive)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 135, in start
    reraise(RunnerNotStartedError,
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\third_party\six\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
mozrunner.errors.RunnerNotStartedError: Failed to start the process: too many values to unpack (expected 18)

INFO STDERR: Exception ignored in:
INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x00000189F97B6940>
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 174, in __del__
INFO STDERR:
INFO STDERR: if handle or self._job or self._io_port:
INFO STDERR: AttributeError
INFO STDERR: :
INFO STDERR: 'Process' object has no attribute '_job'
ERROR Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
ValueError: too many values to unpack (expected 18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\testrunner.py", line 227, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 748, in start
    self.instance = self.instance_manager.get()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 350, in get
    self.pending = self.start()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 312, in start
    runner.start(debug_args=debug_args, interactive=self.debug_info and self.debug_info.interactive)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 135, in start
    reraise(RunnerNotStartedError,
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\third_party\six\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
mozrunner.errors.RunnerNotStartedError: Failed to start the process: too many values to unpack (expected 18)

INFO STDERR: Exception ignored in:
INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x00000189F97B6940>
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 174, in __del__
INFO STDERR:
INFO STDERR: if handle or self._job or self._io_port:
INFO STDERR: AttributeError
INFO STDERR: :
INFO STDERR: 'Process' object has no attribute '_job'
ERROR Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
ValueError: too many values to unpack (expected 18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\testrunner.py", line 227, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 748, in start
    self.instance = self.instance_manager.get()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 350, in get
    self.pending = self.start()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 312, in start
    runner.start(debug_args=debug_args, interactive=self.debug_info and self.debug_info.interactive)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 135, in start
    reraise(RunnerNotStartedError,
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\third_party\six\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
mozrunner.errors.RunnerNotStartedError: Failed to start the process: too many values to unpack (expected 18)

INFO STDERR: Exception ignored in:
INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x00000189F97B6940>
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 174, in __del__
INFO STDERR:
INFO STDERR: if handle or self._job or self._io_port:
INFO STDERR: AttributeError
INFO STDERR: :
INFO STDERR: 'Process' object has no attribute '_job'
ERROR Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
ValueError: too many values to unpack (expected 18)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\testrunner.py", line 227, in init
    self.browser.start(group_metadata=group_metadata, **self.browser_settings)
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 748, in start
    self.instance = self.instance_manager.get()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 350, in get
    self.pending = self.start()
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\wptrunner\wptrunner\browsers\firefox.py", line 312, in start
    runner.start(debug_args=debug_args, interactive=self.debug_info and self.debug_info.interactive)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\browser.py", line 85, in start
    BaseRunner.start(self, *args, **kwargs)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 135, in start
    reraise(RunnerNotStartedError,
  File "C:\Users\Kagami\Documents\GitHub\wpt\tools\third_party\six\six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozrunner\base\runner.py", line 131, in start
    process.run(self.timeout, self.output_timeout)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 842, in run
    self.proc = self.Process([self.cmd] + self.args, **args)
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 141, in __init__
    subprocess.Popen.__init__(self, args, **kwargs)
  File "C:\mozilla-build\python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 270, in _execute_child
    (args, executable, preexec_fn, close_fds,
mozrunner.errors.RunnerNotStartedError: Failed to start the process: too many values to unpack (expected 18)

INFO STDERR: Exception ignored in:
INFO STDERR: <function ProcessHandlerMixin.Process.__del__ at 0x00000189F97B6940>
INFO STDERR: Traceback (most recent call last):
INFO STDERR:   File "C:\Users\Kagami\Documents\GitHub\wpt\_venv3\Lib\site-packages\mozprocess\processhandler.py", line 174, in __del__
INFO STDERR:
INFO STDERR: if handle or self._job or self._io_port:
INFO STDERR: AttributeError
INFO STDERR: :
INFO STDERR: 'Process' object has no attribute '_job'
CRITICAL Max restarts exceeded
Ran 0 tests finished in 0.3 seconds.
  • 0 ran as expected. 0 tests skipped.

CRITICAL No tests ran
```

</details>

### PR DESCRIPTION
**Pull request by saschanaz**
Closes #26353

### CODE REVIEW

**Comment by Hexcles** [comment]
Failures are irrelevant and should be fixed by #26433

**Review by Hexcles — APPROVED** [review]
