### ISSUE TITLE
daily Servo runs have failed since January

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#36326]
Currently the latest Servo run on wpt.fyi is from January.

This appears to be a regression from https://github.com/web-platform-tests/wpt/pull/33289, as everything fails with:

```
AttributeError: 'ServoRefTestExecutor' object has no attribute 'reftest_screenshot'

 0:19.70 CRITICAL Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 151, in start_runner
    executor = executor_cls(logger, browser, **executor_kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 193, in __init__
    self.implementation = RefTestImplementation(self)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 391, in __init__
    self.reftest_screenshot = executor.reftest_screenshot
AttributeError: 'ServoRefTestExecutor' object has no attribute 'reftest_screenshot'
```

I don't have a strong opinion about the Servo runs; @jdm seems to (still) be the top committer to Servo, in case he has any strong opinion. If we're not gonna fix care about fixing this, we should probably stop wasting Taskcluster time on these failing jobs.

cc @jgraham

**Comment by jdm** [comment]
Agreed. I don't think it's worth continuing the Servo runs until there's more regular activity happening again.

**Comment by gsnedders** [comment]
Let's keep this open to track dropping the Servo runs.
