### PR TITLE
Fix #36326: stop daily runs of Servo

### LINKED ISSUE #36326: daily Servo runs have failed since January
Currently the latest Servo run on wpt.fyi is from January.

This appears to be a regression from https://github.com/web-platform-tests/wpt/pull/33289, as everything fails with:

```
AttributeError: 'ServoRefTestExecutor' object has no attribute 'reftest_screenshot'

 0:19.70 CRITICAL Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 151, in start_runner
    executor = executor_cls(logger, browser, **executor_kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 193, in __init__
    self.implementation = RefTestImplementation(self)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 391, in __init__
    self.reftest_screenshot = executor.reftest_screenshot
AttributeError: 'ServoRefTestExecutor' object has no attribute 'reftest_screenshot'
```

I don't have a strong opinion about the Servo runs; @jdm seems to (still) be the top committer to Servo, in case he has any strong opinion. If we're not gonna fix care about fixing this, we should probably stop wasting Taskcluster time on these failing jobs.

cc @jgraham

### PR DESCRIPTION
**Pull request by gsnedders**
Fixes #36326.

These have been broken since January, and there's been few people
noticing or having the interest to fix them, so let's just stop using
Taskcluster capacity to run it except when explicitly triggered.

### CODE REVIEW

**Review by foolip — APPROVED** [review]

**Review by jdm — APPROVED** [review]

**Comment by gsnedders** [comment]
The Azure Pipelines failure is tracked in #36504.
