### PR TITLE
Credential Management: Test rejection of incompatible types in get()

### PR DESCRIPTION
**Pull request by mohamedamir**
This PR adds Web Platform Tests for the restrictions introduced in https://github.com/w3c/webappsec-credential-management/pull/261.

  The specification now requires that navigator.credentials.get() must reject with a
  NotSupportedError if it is called with a combination of credential types that are not
  explicitly allowed to be mixed in the same request. 

  Changes:
   - Updated credential-management/credentialscontainer-get-basics.https.html to include a
     new test suite for invalid type combinations.
   - Verified that requesting combinations such as password + publicKey, otp + identity, and
     others result in a promise rejected with NotSupportedError.
   - The test covers the following credential types: 
     - PasswordCredential
     - FederatedCredential
     - PublicKeyCredential
     - OTPCredential
     - IdentityCredential (FedCM)

  This ensures that implementations correctly validate the "types allowed in the same get()
  request" registry column as defined in the updated spec.

### CODE REVIEW

**Review by nsatragno — APPROVED** [review]
Approved, thank you!

File: credential-management/credentialscontainer-get-basics.https.html [hunk 1]
```diff
@@ -55,6 +55,40 @@
...
+        t,
+        "NotSupportedError",
+        navigator.credentials.get(options)
+      );
+    }
+  }, "Calling navigator.credentials.get() with invalid combinations of credential types.");
+
+  promise_test(async (t) => {
+    try {
+      await navigator.credentials.get({
```
Comment (marcoscaceres) [inline credential-management/credentialscontainer-get-basics.https.html]: maybe we can use promise_rejects_dom?

Comment (mohamedamir) [reply credential-management/credentialscontainer-get-basics.https.html]: Done!

**Comment by mohamedamir** [comment]
@marcoscaceres as per our discussion today, I will go ahead and merge this!
