### ISSUE TITLE
Python generates TypeError in pickle.dump when using wpt update-expectations

### ISSUE THREAD

**Issue by stp-ekioh** [web-platform-tests/wpt#26434]
Hi - I've been trying to use "wpt update-expectations" to generate some test expectation data for our Flow browser and have run into a couple of problems.  Having run some tests (in this case using Firefox for illustration) I'm running the following command on Ubuntu 20.10 to generate the new expectation data:

    ./wpt update-expectations --product firefox firefox.log

which produces the following error:

```
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/stp/wpt-ekioh/tools/wpt/wpt.py", line 173, in main
    rv = script(*args, **kwargs)
  File "/home/stp/wpt-ekioh/tools/wpt/update.py", line 32, in update_expectations
    updater.run()
  File "/home/stp/wpt-ekioh/tools/wptrunner/wptrunner/update/update.py", line 179, in run
    self.state.kwargs = self.kwargs
  File "/home/stp/wpt-ekioh/tools/wptrunner/wptrunner/update/state.py", line 57, in __setattr__
    self.save()
  File "/home/stp/wpt-ekioh/tools/wptrunner/wptrunner/update/state.py", line 115, in save
    pickle.dump(self, f)
TypeError: write() argument must be str, not bytes
```
It looks to me as if the problem is being caused by the fact that the SavedState load and save methods aren't opening the file in binary mode, but even if I fix that I then run into further problems.  This is all leading me to question if I'm going about this the right way and what can be expected to work and on what OS.

FWIW I've also tried doing this on macOS (where I had to use --py3 to avoid some virtualenv errors) but got exactly the same problem.  I'm not at all sure that I'm doing any of this right, so any advice would of course be appreciated :-)

Cheers!

**Comment by stephenmcgruer** [comment]
cc @jgraham as the most knowledgeable about `update-expectations`

**Comment by jgraham** [comment]
https://github.com/web-platform-tests/wpt/pull/26503 fixes this for me using Py3 on linux. Can you try that branch and let me know what further errors you see?

**Comment by stp-ekioh** [comment]
Thanks for the update - with that change in place the update-expectations command appears to work on Ubuntu 20.10 using Python 3, and generates a bunch expectation data for both Firefox and Flow.  However, If I try on my Mac I get the following error:

```
Don't Panic! ~/vbox-share/wpt $ ./wpt --py3 update-expectations --product flow output.log
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/Users/stp/vbox-share/wpt/tools/wpt/wpt.py", line 173, in main
    rv = script(*args, **kwargs)
  File "/Users/stp/vbox-share/wpt/tools/wpt/update.py", line 31, in update_expectations
    updater = WPTUpdate(logger, **kwargs)
  File "/Users/stp/vbox-share/wpt/tools/wptrunner/wptrunner/update/update.py", line 157, in __init__
    self.state = SavedState(logger)
  File "/Users/stp/vbox-share/wpt/tools/wptrunner/wptrunner/update/state.py", line 8, in __new__
    rv = cls.load(logger)
  File "/Users/stp/vbox-share/wpt/tools/wptrunner/wptrunner/update/state.py", line 102, in load
    rv = pickle.load(f)
TypeError: __new__() missing 1 required positional argument: 'logger'
```
Annoyingly I've not been able to convince Firefox to run the tests at all on my Mac, and so can't prove that it's not just a Flow specific problem.  The exact same code has worked on Ubuntu though, so I don't think it's a  problem with something that we've introduced...

**Comment by jgraham** [comment]
@gsnedders does this ring any bells to you?

**Comment by gsnedders** [comment]
@jgraham no, it doesn't

IIRC unpickling issues are really awkward to figure out given the implementation is a bit opaque…

@stp-ekioh my best suggestion is to add `sys.modules['_pickle'] = None` at the top of `wpt/wpt` (probably right after the `sys` import before we import anything else; this disables the C extension module and makes pickle use its more easily debugged Python impl) and try running `python3 --pdb ./wpt […]` and see if you can see what class is being unpickled there?

**Comment by stp-ekioh** [comment]
Thanks for the info - looking at `load_newobj` in pickle.py, it seems as though as the class is `<class 'wptrunner.update.state.SavedState'>` which has got an empty argument list.  Looking at class BaseState it seems to be expecting to receive a logger.  I don't know if that helps at all.  Also no idea why this should be different on macOS.

**Comment by gsnedders** [comment]
> Also no idea why this should be different on macOS.

Potentially something multiprocessing related, as nowadays it uses pickle to move things between processes.

But `wptrunner.update.state` does look broken; I can't see how it could ever succeed on any platform. I think the contents of that `__new__` should just be in the `__init__`?
