### ISSUE TITLE
partially initialized module 'webdriver.client' has no attribute 'Session'

### ISSUE THREAD

**Issue by WeizhongX** [web-platform-tests/wpt#29489]
After roll latest wpt from github.com to chromium, we met issue as below when run wpt on the bots. Can somebody pls take a look?

-----------------------------------------

Traceback (most recent call last):
  File "/b/s/w/ir/third_party/wpt_tools/wpt/wpt", line 11, in <module>
    wpt.main()
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wpt/wpt.py", line 179, in main
    rv = script(*args, **kwargs)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wpt/run.py", line 848, in run
    rv = run_single(venv, **wptrunner_kwargs) > 0
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wpt/run.py", line 855, in run_single
    return wptrunner.start(**kwargs)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 414, in start
    rv = not run_tests(**kwargs) or logged_critical.has_log
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/wptrunner.py", line 167, in run_tests
    product = products.Product(config, product)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/products.py", line 33, in __init__
    module = product_module(config, product)
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/products.py", line 23, in product_module
    module = importlib.import_module("wptrunner.browsers." + product)
  File "/b/s/w/ir/.task_template_vpython_cache/vpython/57dfd5/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 778, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/browsers/android_weblayer.py", line 4, in <module>
    from .chrome import executor_kwargs as chrome_executor_kwargs
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/browsers/chrome.py", line 7, in <module>
    from ..executors.executorwebdriver import (WebDriverTestharnessExecutor,  # noqa: F401
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 31, in <module>
    import webdriver as client
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/__init__.py", line 3, in <module>
    from .client import (
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/client.py", line 4, in <module>
    from .bidi.client import BidiSession
  File "/b/s/w/ir/third_party/wpt_tools/wpt/tools/webdriver/webdriver/bidi.py", line 6, in <module>
    class BidiSession(client.Session):
AttributeError: partially initialized module 'webdriver.client' has no attribute 'Session' (most likely due to a circular import)

**Comment by KyleJu** [comment]
Looks like it is caused by https://github.com/web-platform-tests/wpt/pull/28381

**Comment by WeizhongX** [comment]
@jgraham, can you pls take a look?

**Comment by KyleJu** [comment]
It could be wrong but it looks like it is trying to import `from .bidi.client import BidiSession`, the `BidiSession` from tools/webdriver/webdriver/bidi/client.py, but instead it is fetching  `BidiSession` in wpt/tools/webdriver/webdriver/bidi.py

**Comment by WeizhongX** [comment]
Looks like this is due to an issue in our rolling script. Unassign @jgraham for now.

**Comment by KyleJu** [comment]
This has been resolved
