### PR TITLE
Add support for Epiphany web browser

### PR DESCRIPTION
**Pull request by mcatanzaro**
It's similar to the existing WebKit support, but a bit easier to use as
you can simply ./wpt run epiphany

Opportunistically improve a Servo error message, since we are adding
similar error messages below and consistency is nice.

Next step is to figure out how to run the tests under Weston. Currently they run in my normal desktop session, stealing input and guaranteeing that the automation tests all take forever and fail when I manually grab input back to whatever I was doing. That's why I don't have test results yet.

### CODE REVIEW

**Comment by mcatanzaro** [comment]
The remaining CI failure at least seems to be unrelated:

```
manifest/tests/test_manifest.py:70: in <module>
    unique_by=lambda x: x.rel_path))
E   TypeError: lists() got an unexpected keyword argument 'average_size'
```

I found the documentation of the python-hypothesis library, [and the `average_size` parameter indeed doesn't exist](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=lists#hypothesis.strategies.lists). The broken code hasn't changed since https://github.com/web-platform-tests/wpt/commit/8777171a5568e9fa967ef7a807dc400d89a07637 so not sure what could have changed.

File: tools/wptrunner/requirements_epiphany.txt [hunk 1]
```diff
@@ -0,0 +1,2 @@
+mozprocess == 0.26
+selenium == 3.9.0
```
Comment (jgraham) [inline tools/wptrunner/requirements_epiphany.txt]: I'm not sure that selenium is required since `ExecutorWebDriver` doesn't use it (some existing files are wrong here). We could probably add `mozprocess` to `requirements.txt` and eliminate a bunch of `requirements_*` files.

File: tools/wpt/run.py [hunk 2]
```diff
@@ -422,7 +422,7 @@ def setup_kwargs(self, kwargs):
             binary = self.browser.find_binary(self.venv.path, None)
 
             if binary is None:
-                raise WptrunError("Unable to find servo binary on the PATH")
+                raise WptrunError("Unable to find servo binary in PATH")
```
Comment (jgraham) [inline tools/wpt/run.py]: Not sure that this was a change important enough to make here.

**Review by jgraham — APPROVED** [review]
This looks good, but there are a couple of changes I would appreciate before landing.

File: tools/wpt/browser.py [hunk 3]
```diff
@@ -758,3 +758,33 @@ def install_webdriver(self, dest=None, channel=None):
...
+        raise NotImplementedError
+
+    def version(self, binary=None, webdriver_binary=None):
+        if binary is None:
+            return None
+        output = call(binary, "--version")
+        if output:
+            # Stable release output looks like: "Web 3.30.2"
+            # Tech Preview output looks like "Web 3.31.3-88-g97db4f40f"
+            # So split off the first word, then truncate after the first hyphen.
```
Comment (foolip) [inline tools/wpt/browser.py]: Why not include the whole 3.31.3-88-g97db4f40f? Code that processes the version string (in wpt.fyi) could make it prettier if needed, but having the full string seems potentially useful if there can be updates which don't change the leading part. @lukebjerring opinions?

File: tools/wptrunner/wptrunner/browsers/epiphany.py [hunk 4]
```diff
@@ -0,0 +1,75 @@
+from .base import Browser, ExecutorBrowser
+from .base import get_timeout_multiplier   # noqa: F401
+from .webkit import WebKitBrowser
+from ..executors import executor_kwargs as base_executor_kwargs
+from ..executors.executorwebdriver import (WebDriverTestharnessExecutor,  # noqa: F401
```
Comment (foolip) [inline tools/wptrunner/wptrunner/browsers/epiphany.py]: Nice to see ExecutorWebDriver being reused :D

**Review by foolip — APPROVED** [review]

File: tools/wptrunner/requirements_epiphany.txt (hunk 1 above)
Comment (mcatanzaro) [reply tools/wptrunner/requirements_epiphany.txt]: OK, I was confused by that too, but just copy/pasted from requirements_webkit.txt.

(What is `mozprocess` for?)

File: tools/wpt/run.py (hunk 2 above)
Comment (mcatanzaro) [reply tools/wpt/run.py]: Er, I guess I'll leave it then? Of course it's very easy to remove if desired.

(Trivia: it most likely comes from Spanish, which uses "en" for both "in" and "on," making it rather difficult to pick the right one when writing in English.)

File: tools/wpt/browser.py (hunk 3 above)
Comment (lukebjerring) [reply tools/wpt/browser.py]: Can keep it + adapt to this format - fyi @Hexcles - this may need to be handled in our version-string special cases.

Comment (Hexcles) [reply tools/wpt/browser.py]: Is "Web" the name of the application? If so, the convention is to strip it, but all the remaining stuff can be kept, e.g. `3.30.2` or `3.31.3-88-g97db4f40f`.

Comment (mcatanzaro) [reply tools/wpt/browser.py]: The codename of the project is "Epiphany" and that's probably what we'd want to display on wpt.fyi, but the actual user-visible name is just "Web". (We can also write "GNOME Web" when needed to disambiguate.)

**Comment by mcatanzaro** [comment]
OK, addressed all comments here. I think the only remaining problem is:

> The remaining CI failure at least seems to be unrelated:
> 
> ```
> manifest/tests/test_manifest.py:70: in <module>
>     unique_by=lambda x: x.rel_path))
> E   TypeError: lists() got an unexpected keyword argument 'average_size'
> ```
> I found the documentation of the python-hypothesis library, [and the `average_size` parameter indeed doesn't exist](https://hypothesis.readthedocs.io/en/latest/data.html?highlight=lists#hypothesis.strategies.lists). The broken code hasn't changed since [8777171](https://github.com/web-platform-tests/wpt/commit/8777171a5568e9fa967ef7a807dc400d89a07637) so not sure what could have changed.

which has me stumped, since other pull requests don't seem to be hitting this failure.

**Comment by foolip** [comment]
@mcatanzaro, some tests only run based on what has changed in a PR, so it's possible it's already broken but just not showing up. I'll send a PR to probe for currently failing tests.

**Comment by foolip** [comment]
Yep, the failure was already present: https://travis-ci.com/web-platform-tests/wpt/jobs/170769863

@jgraham I think we should admin merge this, but do you have final thoughts?

**Comment by jgraham** [comment]
There are flake8 errors specific to this PR. Please fix those before merging.

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/14890 should fix the existing failure.

**Comment by foolip** [comment]
But more failures will remain :(

**Comment by mcatanzaro** [comment]
> There are flake8 errors specific to this PR. Please fix those before merging.

Hi @jgraham, where can I see these failures?

**Comment by foolip** [comment]
@mcatanzaro flak8 is run as part of "tools/ unittests (Python 2)" and "tools/ unittests (Python 3)" on Travis. I've filed https://github.com/web-platform-tests/wpt/issues/14893 about this not being ideal.

**Comment by mcatanzaro** [comment]
I think flake8 is fixed. There are other failures on travis, but again they look unrelated.

**Comment by foolip** [comment]
Yep, what remains is because of https://github.com/web-platform-tests/wpt/issues/14179 and https://github.com/web-platform-tests/wpt/issues/14894, so I'll merge this now.
