### PR TITLE
Enable back runs of Servo (start with weekly instead of daily for now)

### LINKED ISSUE #36326: daily Servo runs have failed since January
Currently the latest Servo run on wpt.fyi is from January.

This appears to be a regression from https://github.com/web-platform-tests/wpt/pull/33289, as everything fails with:

```
AttributeError: 'ServoRefTestExecutor' object has no attribute 'reftest_screenshot'

 0:19.70 CRITICAL Traceback (most recent call last):
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/testrunner.py", line 151, in start_runner
    executor = executor_cls(logger, browser, **executor_kwargs)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/executorservo.py", line 193, in __init__
    self.implementation = RefTestImplementation(self)
  File "/home/test/web-platform-tests/tools/wptrunner/wptrunner/executors/base.py", line 391, in __init__
    self.reftest_screenshot = executor.reftest_screenshot
AttributeError: 'ServoRefTestExecutor' object has no attribute 'reftest_screenshot'
```

I don't have a strong opinion about the Servo runs; @jdm seems to (still) be the top committer to Servo, in case he has any strong opinion. If we're not gonna fix care about fixing this, we should probably stop wasting Taskcluster time on these failing jobs.

cc @jgraham

### PR DESCRIPTION
**Pull request by clopez**
The servo reftest executor was fixed in 112c0145a2 (#37610) so let's enable back again the daily runs of servo on the WPT CI.

This reverts commit a633361f58 "Fix #36326: stop daily runs of Servo"

//CC @jgraham @gsnedders @jdm

### CODE REVIEW

**Comment by gsnedders** [comment]
Are you/others planning on looking at the Servo results regularly? Regardless, with the current rate of Servo development, I'm not sure it's worthwhile running this more than weekly?

**Comment by clopez** [comment]
Yes, we are planning to look at the Servo builds regularly. Also there is going to be renewed activity on Servo development starting soon next year.

Having said that, it is not big trouble to have weekly runs instead of daily. I can change that in the patch if you want.

**Comment by gsnedders** [comment]
> Having said that, it is not big trouble to have weekly runs instead of daily. I can change that in the patch if you want.

I mean, it should probably be more down to @jgraham than me—after all, Mozilla are the one providing hosting. But, like, my gut reaction is to start off as weekly, and we can always change it to daily later if it is getting enough usage.

**Comment by clopez** [comment]
Ok. Let's start with weekly runs and then we can increase the frequency later if it gets enough usage

**Comment by clopez** [comment]
The CI is giving again [errors not related to this patch](https://github.com/web-platform-tests/wpt/pull/37645/checks?check_run_id=10277242628)

```
web-platform-test
~~~~~~~~~~~~~~~~~
Ran 354 checks (204 subtests, 150 tests)
Expected results: 351
Skipped: 1 tests
Unexpected results: 2
  subtest: 2 (2 pass)

Unexpected Results
------------------
/infrastructure/server/http2-websocket.sub.h2.any.html
  UNEXPECTED-PASS WSS over h2
/infrastructure/server/http2-websocket.sub.h2.any.worker.html
  UNEXPECTED-PASS WSS over h2
```

I will retry re-running the CI another day

**Comment by clopez** [comment]
The CI keeps giving unrelated errors :(

**Comment by foolip** [comment]
https://github.com/web-platform-tests/wpt/pull/37743 should have fixed those errors, let's close and reopen once more...

**Comment by jcscottiii** [comment]
The infrastructure/ tests: macOS check should not have failed. Re-running it.

**Review by jgraham — APPROVED** [review]
Weekly runs seems fine to me.
