### ISSUE TITLE
REGRESSION(980adbd): Edge runs failing

### ISSUE THREAD

**Issue by gsnedders** [web-platform-tests/wpt#47907]
After https://github.com/web-platform-tests/wpt/commit/980adbd1736ec466358831b34c0206cf668fe98c (from https://github.com/web-platform-tests/wpt/pull/47850), all the Edge runs are failing with:

```
 4:15.78 CRITICAL Traceback (most recent call last):
  File "D:\a\1\s\tools\wptrunner\wptrunner\testrunner.py", line 211, in start_runner
    with TestRunner(logger,
         ^^^^^^^^^^^^^^^^^^
  File "D:\a\1\s\tools\wptrunner\wptrunner\testrunner.py", line 88, in __init__
    self.executor = executor_implementation.executor_cls(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\1\s\tools\wptrunner\wptrunner\executors\executorwebdriver.py", line 953, in __init__
    self.protocol = self.protocol_cls(self,
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\1\s\tools\wptrunner\wptrunner\executors\executorchrome.py", line 234, in __init__
    if browser.leak_check:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'ExecutorBrowser' object has no attribute 'leak_check'
```

I don't know if @jonathan-j-lee's existing follow-up on #47903 already fixes this, but to have some issue filed here and to make sure this is known: hi!

**Comment by jonathan-j-lee** [comment]
I ended up reverting #47850 for now to fix the breakage ASAP. #47903 contains the reland, which I'll watch more closely.
